//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Othello.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marcador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marcador()
        {
            this.Tablero = new HashSet<Tablero>();
        }
    
        public int ID_Marcador { get; set; }
        public Nullable<int> NoFichasNegras { get; set; }
        public Nullable<int> NoFichasBlancas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tablero> Tablero { get; set; }
    }
}
