//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Othello.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IPC2_2S2020Entities : DbContext
    {
        public IPC2_2S2020Entities()
            : base("name=IPC2_2S2020Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ficha> Ficha { get; set; }
        public virtual DbSet<Marcador> Marcador { get; set; }
        public virtual DbSet<Partida> Partida { get; set; }
        public virtual DbSet<Sala> Sala { get; set; }
        public virtual DbSet<Tablero> Tablero { get; set; }
        public virtual DbSet<TipoPartida> TipoPartida { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<TipoReporte> TipoReporte { get; set; }
        public virtual DbSet<Torneo> Torneo { get; set; }
        public virtual DbSet<Reporte> Reporte { get; set; }
    }
}
