//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Othello.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public int ID_Reporte { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idTipoReporte { get; set; }
    
        public virtual TipoReporte TipoReporte { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
